# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/322401dd-1ba5-4223-8933-51572d8805e2";
  #     fsType = "btrfs";
  #     options = [ "subvol=@home" ];
  #   };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/322401dd-1ba5-4223-8933-51572d8805e2";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ed993ae3-28c8-46c0-a7fd-6e23c675f85b".device =
    "/dev/disk/by-uuid/ed993ae3-28c8-46c0-a7fd-6e23c675f85b";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E20E-CAF8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
}
