# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4a787f53-75f7-4e02-8b29-d2569680e35b";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:2" ];
    };

  boot.initrd.luks.devices."luks-cf51b511-083f-4e57-9257-c5e363d813bc".device = "/dev/disk/by-uuid/cf51b511-083f-4e57-9257-c5e363d813bc";


  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4a787f53-75f7-4e02-8b29-d2569680e35b";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd:2" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CE2-B969";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.production;

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

}
