{
  imports = [
    ./bluetooth.nix
    ./bootloader.nix
    ./dev-dependencies.nix
    ./env.nix
    ./flatpak.nix
    ./hyprland.nix
    ./i18n.nix
    ./net.nix
    ./nvidia.nix
    ./qt.nix
    ./sound.nix
    ./special-configs.nix
    ./sys-utils.nix
    ./trim.nix
    ./user.nix
    ./virtualization-containerization.nix
    ./xserver.nix
    ./zram.nix
  ];
}
